# Generated by Django 3.1.2 on 2020-10-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kekeriders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kekerider',
            old_name='home_address',
            new_name='address',
        ),
    ]
